### ISSUE TITLE
Incorrect syntax in Ansible code when using Script Builder

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/home#216]
### What You Are Seeing?

The full playbook code available when using script builder has incorrect syntax when referencing variables
### How Did You Get This To Happen? (Steps to Reproduce)

1. Use Script Builder to generate Ansible playbook code
2. Create a playbook in VSCode and apply copied code from Script builder
3. Commit code to Git repository associated with a Project
4. Create a template that uses a correct inventory and references your Project
5. Execute task against your template
6. Observe syntax errors coming from ansible output

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): Windows Server 2019
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1
* Chocolatey version (Run `choco --version`): 1.2.0

### Output Log

No logs to provide

┆Issue is synchronized with this [Gitlab issue](https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1185) by [Unito](https://www.unito.io)
┆Link To Issue: https://gitlab.com/chocolatey/community-infrastructure/community.chocolatey.org/-/issues/1185

**Comment by steviecoaster** [comment]
Here is the offending code:

```yaml
- name: Add Internal Repository
    win_chocolatey_source:
      name: ChocolateyInternal
      state: present
      source: {{ nuget_repository_url }}
      # source_username: {{ nuget_repository_username }}
      # source_password: {{ nuget_repository_password }}
      priority: 1
```

Ansible is reporting incorrect syntax near the variable flower brackets. Correct syntax is:

```yaml
- name: Add Internal Repository
    win_chocolatey_source:
      name: ChocolateyInternal
      state: present
      source: ""{{ nuget_repository_url }}""
      # source_username: ""{{ nuget_repository_username }}""
      # source_password: ""{{ nuget_repository_password }}""
      priority: 1
```
