### ISSUE TITLE
Script Builder: Support Salt Project as Config Management Option

### ISSUE THREAD

**Issue by ScriptAutomate** [chocolatey/home#271]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

The script builder includes how to install packages for Puppet, PowerShell DSC, Chef, etc. but not [Salt Project](https://saltproject.io/).

- [Salt Reference Docs: States - Chocolatey](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.chocolatey.html)

### Describe The Solution. Why is it needed?

For example, if looking at [rsync](https://community.chocolatey.org/packages/rsync), a default **3. Copy Your Script** step for Salt would look like:

```yaml
InstallRsync:
  chocolatey.installed:
    - name: rsync
    - version: '6.2.9'
    - source: 'http://internal/odata/repo'
```
